/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XhaKLyCIG0e
 */
import { FilesResponse } from "@/app/api/files/route";
import { headers } from "next/headers";
import Link from "next/link";

export async function VideoList() {
  const host = headers().get("host");
  const res = await fetch(`http://${host}/api/files/`, {
    method: "GET",
    cache: "no-store",
  });
  const files: FilesResponse = await res.json();
  const mp4Files = files.filter((f) => f.key.endsWith(".mp4"));
  return (
    <section className="h-screen w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-purple-400 via-pink-500 to-red-500">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl text-white">
              Multi-modal Starter Kit
            </h1>
            <p className="max-w-[900px] text-white md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Explore our collection of starter videos to kickstart your
              multi-modal project.
            </p>
          </div>
          <ul className="grid gap-2 py-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-2">
            {mp4Files.map((f, index) => {
              return (
                <li key={f.key} className="flex flex-col items-center gap-2">
                  <img
                    alt="Video 1"
                    className="w-full aspect-[16/9] object-cover rounded-lg"
                    height="200"
                    //TODO - replace this with the actual image
                    src="/sci-fi.png"
                    width="350"
                  />
                  <Link
                    className="text-lg font-medium hover:underline underline-offset-4 text-white"
                    href={{
                      pathname: "/files/play",
                      query: {
                        name: f.key,
                      },
                    }}
                  >
                    {f.displayName}
                  </Link>
                  <p className="text-sm text-white">
                    Get started with multi-modal by understanding the basics.
                  </p>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    </section>
  );
}
